In [1]:
import numpy as np

In [2]:
def S(R: np.ndarray) -> np.ndarray:
    return np.matmul(R.T, R)

In [124]:
R = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [128]:
D = np.array([[0, 0, 0], [0, 0, 1], [0, 0, 0]])

In [129]:
S(R+D)

array([[ 66,  78,  94],
       [ 78,  93, 113],
       [ 94, 113, 139]])

In [132]:
print(D)
print(R)
print(np.matmul(D.T, R) + np.matmul(R.T, D))

[[0 0 0]
 [0 0 1]
 [0 0 0]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 0  0  4]
 [ 0  0  5]
 [ 4  5 12]]


In [68]:
np.matmul(D.T, R) + np.matmul(R.T, D)

array([[0.  , 0.  , 0.  ],
       [0.  , 0.12, 0.09],
       [0.  , 0.09, 0.  ]])

In [60]:
np.matmul(R.T, D)

array([[0.001, 0.   , 0.001],
       [0.002, 0.06 , 0.022],
       [0.003, 0.09 , 0.032]])

In [150]:
X = np.random.randint(1, high=10, size=(4, 4))
D = np.random.rand(4,4)/10

In [151]:
S = np.matmul(X.T, X)

In [153]:
np.matmul(X.T+D.T, X+D)

array([[ 94.56923984, 103.65029268,  73.44488209, 100.71711383],
       [103.65029268, 125.9062035 ,  81.34239921, 129.90525907],
       [ 73.44488209,  81.34239921,  80.19891722,  80.94863977],
       [100.71711383, 129.90525907,  80.94863977, 139.91806085]])

In [157]:
np.matmul(X.T, X) + np.matmul(2*X, D)

array([[ 94.3077111 , 102.93817597,  73.54801381, 100.57273458],
       [103.79497735, 126.0220095 ,  82.13422582, 129.09088993],
       [ 74.03062396,  82.08486815,  81.29416974,  80.9814365 ],
       [100.59551878, 129.82716726,  80.87406282, 138.83061949]])

In [5]:
f(
    """
    hello
    """
    z
    "helo"
)

SyntaxError: invalid syntax (<ipython-input-5-0b7f04130b79>, line 5)

In [2]:
def f(*args):
    pass

In [4]:
z = "d"