In [1]:
%load_ext autoreload

%autoreload 2

In [2]:
import numpy as np

from mlapp_models.hidden_markov_model import HiddenMarkovModel

# Hidden Markov Model

## Create Data

In [3]:
# Set the true parameters
Psi = np.array([[0.95, 0.05], [0.1, 0.9]])
B = np.array(
    [
        [1 / 6, 1 / 10],
        [1 / 6, 1 / 10],
        [1 / 6, 1 / 10],
        [1 / 6, 1 / 10],
        [1 / 6, 1 / 10],
        [1 / 6, 5 / 10],
    ]
)
pi = np.array([2 / 3, 1 / 3])

# Create a model to sample from it
true_model = HiddenMarkovModel(2, 6, Psi=Psi, B=B, pi=pi)

Show that, with enough samples, we can recover the parameters (up to graph isomorphism).

In [4]:
samples = true_model.sample([100] * 100)

## Fit Model

In [5]:
model = HiddenMarkovModel(2, 6)

In [6]:
model.fit(samples, num_iter=1000)

100%|██████████████████████████████████████████████████████████████████████████████| 1000/1000 [04:23<00:00,  3.80it/s]


In [7]:
print("MLE Psi", model.Psi, "MLE B", model.B, "MLE pi", model.pi, sep="\n")

MLE Psi
[[0.90424317 0.09575683]
 [0.05163824 0.94836176]]
MLE B
[[0.08718635 0.16506933]
 [0.09621213 0.16669855]
 [0.10419679 0.16382442]
 [0.09724937 0.16875161]
 [0.09083798 0.17323998]
 [0.52431738 0.16241611]]
MLE pi
[0.28507755 0.71492245]


In [9]:
print(
    "True Psi",
    true_model.Psi,
    "True B",
    true_model.B,
    "True pi",
    true_model.pi,
    sep="\n",
)

True Psi
[[0.95 0.05]
 [0.1  0.9 ]]
True B
[[0.16666667 0.1       ]
 [0.16666667 0.1       ]
 [0.16666667 0.1       ]
 [0.16666667 0.1       ]
 [0.16666667 0.1       ]
 [0.16666667 0.5       ]]
True pi
[0.66666667 0.33333333]
